version: 2.1
orbs:
  # "cypress-io/cypress@1" installs the latest published
  # version "1.x.y" of the orb. We recommend you then use
  # the strict explicit version "cypress-io/cypress@1.x.y"
  # to lock the version and prevent unexpected CI changes
  cypress: cypress-io/cypress@3.3.1
jobs:
  # 👇 Adds Chromatic as a job
  chromatic-deployment:
    docker:
      - image: cypress/included:13.12.0
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: yarn install
  build:
    working_directory: ~/sanity
    docker:
      - image: cypress/included:13.12.0
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: Run Jest Tests
          command: npm test
      - run:
          name: Codecov
          command: curl -Os https://uploader.codecov.io/latest/linux/codecov && chmod +x codecov && ./codecov
    parallelism: 6
workflows:
  # 👇 Adds Chromatic to the workflow
  chromatic-deploy:
    jobs:
      - build:
          name: Build Next.js project
      - chromatic-deployment: # 👈 Runs the job implemented above
          name: Yarn install
      - cypress/run:
          name: Run Cypress E2E tests          
          start: npm run dev
          executor: cypress/base-14
          wait-on: "http://localhost:3000"
          # there are no jobs to follow this one
          # so no need to save the workspace files (saves time)
          no-workspace: true
          parallelism: 8
